[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jayzuss1023", email = "jesus.flo369@gmail.com" }
]
requires-python = ">=3.11,<3.14"
dependencies = [
    "alchemy>=20.5",
    "clerk-backend-api>=4.0.0",
    "fastapi>=0.125.0",
    "openai>=2.54.0",
    "python-dotenv>=1.2.3",
    "sql>=2022.4.0",
    "uvicorn>=0.52.4",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
